const $=s=>document.querySelector(s);let me=null, data=null;
document.querySelectorAll('.mark').forEach(mark=>{mark.innerHTML='<img src="/assets/pollenit-dots-transparent.png" alt="PollenIT Technologies logo">'});
const profile=p=>({...p,name:p.full_name,email:p.work_email,title:p.designation,earnedEntitlement:Number(p.earned_leave_entitlement),carryForward:Number(p.carry_forward)});
function greeting(){const h=new Date().getHours();return h<12?'Good morning':h<17?'Good afternoon':h<21?'Good evening':'Good night'}
new MutationObserver(()=>{if(me&&data)document.querySelector('.card p').textContent=`${(me.earnedEntitlement+me.carryForward-data.balance).toFixed(1)} days used this year`}).observe($('#elBalance'),{childList:true});
$('.demoAccounts').innerHTML='<b>Pilot access</b><span>Use your PollenIT work email.</span><span>Use the temporary password sent to you privately.</span>';
const festivalNav=document.createElement('button');festivalNav.className='nav';festivalNav.dataset.page='festivals';festivalNav.innerHTML='✦ <span>Festival holidays</span>';document.querySelector('nav').append(festivalNav);festivalNav.onclick=async()=>{await load();show('festivals');renderFestivals()};
const festivalPage=document.createElement('section');festivalPage.id='festivals';festivalPage.className='page';festivalPage.innerHTML='<div class="policy"><p class="pill">2026 FESTIVAL HOLIDAYS</p><h2>Choose your five holidays</h2><p class="muted" id="festivalCounter"></p><div id="festivalList" class="policyGrid"></div></div>';document.querySelector('main').append(festivalPage);
const selectionsNav=document.createElement('button');selectionsNav.className='nav manager';selectionsNav.dataset.page='festivalSelections';selectionsNav.innerHTML='◈ <span>Festival selections</span>';document.querySelector('nav').append(selectionsNav);const selectionsPage=document.createElement('section');selectionsPage.id='festivalSelections';selectionsPage.className='page';selectionsPage.innerHTML='<div class="policy"><p class="pill">TEAM AVAILABILITY</p><h2>Employee festival selections</h2><div id="festivalSelectionList" class="policyGrid"></div></div>';document.querySelector('main').append(selectionsPage);
async function renderFestivalSelections(){const r=await api('/api/festival-selections');$('#festivalSelectionList').innerHTML=r.employees.map(e=>{const names=(e.festival_holidays||[]).map(d=>(r.festivalOptions.find(x=>x.date===d)||{name:d}).name).join(', ')||'No holidays selected yet';return `<article><b>${e.full_name}</b><h3>${(e.festival_holidays||[]).length} of 5 selected</h3><p>${names}</p></article>`}).join('')}
function renderFestivals(){if(!data)return;const chosen=data.festivalChoices||[],today=new Date().toISOString().slice(0,10);$('#festivalCounter').textContent=`${chosen.length} of 5 festival holidays selected. Selected holidays are excluded from leave-day calculations.`;$('#festivalList').innerHTML=(data.festivalOptions||[]).map(h=>{const selected=chosen.includes(h.date),locked=h.date<=today;return `<article><b>${h.name}</b><h3>${fmt(h.date)}</h3><p>${selected?(locked?'Selected - locked':'Selected - editable until the day before'):'Optional festival holiday'}</p><button class="${selected?'outline':'primary'}" ${selected&&locked?'disabled':''} onclick="${selected?`removeFestival('${h.date}')`:`chooseFestival('${h.date}')`}">${selected?(locked?'Locked':'Remove selection'):'Choose holiday'}</button></article>`}).join('')}
window.chooseFestival=async date=>{try{await api('/api/festival-choice',{method:'POST',body:JSON.stringify({date})});await load();renderFestivals();toast('Festival holiday selected.')}catch(e){toast(e.message)}};
window.removeFestival=async date=>{try{await api('/api/festival-choice/remove',{method:'POST',body:JSON.stringify({date})});await load();renderFestivals();toast('Festival holiday selection removed.')}catch(e){toast(e.message)}};
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opts});const d=r.status===204?{}:await r.json();if(!r.ok)throw new Error(d.error||'Something went wrong.');return d}
const fmt=d=>new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T00:00:00'));
const badge=s=>`<span class="status ${s}">${s[0].toUpperCase()+s.slice(1)}</span>`;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function show(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('shown'));$('#'+page).classList.add('shown');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={dashboard:`${greeting()}, ${me.name.split(' ')[0]}`,request:'Apply for leave',requests:'My leave requests',approvals:'Approvals',team:'Team calendar',policy:'Leave policy',festivals:'Festival holidays'};$('#pageTitle').textContent=titles[page];$('#eyebrow').textContent=new Intl.DateTimeFormat('en-IN',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase();window.scrollTo(0,0)}
async function load(){data=await api('/api/dashboard');me=profile(data.user);$('#userName').textContent=me.name;$('#userTitle').textContent=me.title;$('#userInitials').textContent=me.name.split(' ').map(x=>x[0]).join('').slice(0,2);$('#leaveForm').email.value=me.email;render()}
function render(){const used=(me.earnedEntitlement+me.carryForward-data.balance);$('#elBalance').textContent=data.balance.toFixed(1);$('#elBar').style.width=`${Math.min(100,used/(me.earnedEntitlement+me.carryForward)*100)}%`;document.querySelector('.card small').textContent=`days remaining of ${me.earnedEntitlement+me.carryForward}`;const mine=data.requests;$('#requestRows').innerHTML=mine.map(r=>`<tr><td><b>Earned Leave${r.lwpDays?' + LWP':''}</b></td><td>${fmt(r.start)} - ${fmt(r.end)}</td><td>${r.days}</td><td>${r.reason}</td><td>${badge(r.status)}</td></tr>`).join('')||'<tr><td colspan="5">No requests yet.</td></tr>';const up=mine.find(r=>r.status==='approved'&&r.start>='2026-06-22');$('#upcoming').innerHTML=up?`<div class="dateBox">${new Date(up.start+'T00:00:00').getDate()}<small>${new Intl.DateTimeFormat('en',{month:'short'}).format(new Date(up.start+'T00:00:00')).toUpperCase()}</small></div><div><b>Earned Leave</b><p>${fmt(up.start)} - ${fmt(up.end)} · ${up.days} day${up.days===1?'':'s'}</p></div>`:'<p class="muted">No approved upcoming leave.</p>';const canApprove=['manager','hr'].includes(me.role);document.querySelectorAll('.manager').forEach(x=>x.style.display=canApprove?'flex':'none');$('#pendingBadge').textContent=data.approvals.length;$('#approvalList').innerHTML=data.approvals.map(r=>`<article class="approval"><div class="avatar">${r.employeeName.split(' ').map(x=>x[0]).join('')}</div><div><b>${r.employeeName} <span class="muted">requested ${r.days} day${r.days===1?'':'s'} earned leave${r.lwpDays?` + ${r.lwpDays} LWP`:''}</span></b><p>${fmt(r.start)} - ${fmt(r.end)} · “${r.reason}”<br>Manager: ${badge(r.managerDecision)} &nbsp; HR: ${badge(r.hrDecision)}</p></div><div class="actions"><button class="outline" onclick="decision('${r.id}','rejected')">Decline</button><button class="approve" onclick="decision('${r.id}','approved')">Approve</button></div></article>`).join('')||'<div class="panel"><p class="muted">No requests currently need your approval.</p></div>';$('#teamCalendar').innerHTML=mine.filter(r=>r.status==='approved').map(r=>`<div class="calendarRow"><div class="avatar">${me.name.split(' ').map(x=>x[0]).join('')}</div><div><b>${me.name}</b><p class="muted">Earned Leave</p></div><span>${fmt(r.start)} - ${fmt(r.end)}</span></div>`).join('')||'<p class="muted">No approved time off yet.</p>';}
window.decision=async(id,decision)=>{try{await api(`/api/leave/${id}/decision`,{method:'POST',body:JSON.stringify({decision})});await load();toast(`Request ${decision}.`)}catch(e){toast(e.message)}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const result=await api('/api/login',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});me=profile(result.user);document.body.classList.add('loggedIn');await load();show('dashboard')}catch(err){$('#loginError').textContent=err.message;$('#loginError').classList.add('show')}};
$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});me=null;document.body.classList.remove('loggedIn');$('#loginForm').reset()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#quickApply').onclick=()=>show('request');
const form=$('#leaveForm');function count(){if(!form.start.value||!form.end.value)return 0;let n=0,d=new Date(form.start.value+'T00:00:00'),e=new Date(form.end.value+'T00:00:00');while(d<=e){if(d.getDay()!==0&&d.getDay()!==6)n++;d.setDate(d.getDate()+1)}return form.halfDay.checked?.5:n}form.start.onchange=()=>$('#dayCount').textContent=count();form.end.onchange=()=>$('#dayCount').textContent=count();form.halfDay.onchange=()=>$('#dayCount').textContent=count();form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);try{const r=await api('/api/leave',{method:'POST',body:JSON.stringify({start:f.get('start'),end:f.get('end'),reason:f.get('reason'),halfDay:f.get('halfDay')==='on'})});await load();form.reset();form.email.value=me.email;show('requests');toast(r.request.lwpDays?`Request submitted: ${r.request.earnedDays} EL + ${r.request.lwpDays} LWP.`:'Request sent to Manager and HR.')}catch(err){toast(err.message)}};
api('/api/session').then(async r=>{me=profile(r.user);document.body.classList.add('loggedIn');await load();show('dashboard')}).catch(()=>{});
festivalNav.onclick=async()=>{await load();show('festivals');renderFestivals()};
selectionsNav.onclick=async()=>{show('festivalSelections');await renderFestivalSelections()};
