const $=s=>document.querySelector(s);let me=null, data=null;
$('.demoAccounts').innerHTML='<b>Pilot access</b><span>Use your PollenIT work email.</span><span>Initial password: Welcome@2026</span>';
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opts});const d=r.status===204?{}:await r.json();if(!r.ok)throw new Error(d.error||'Something went wrong.');return d}
const fmt=d=>new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T00:00:00'));
const badge=s=>`<span class="status ${s}">${s[0].toUpperCase()+s.slice(1)}</span>`;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function show(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('shown'));$('#'+page).classList.add('shown');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={dashboard:`Good morning, ${me.name.split(' ')[0]}`,request:'Apply for leave',requests:'My leave requests',approvals:'Approvals',team:'Team calendar',policy:'Leave policy'};$('#pageTitle').textContent=titles[page];window.scrollTo(0,0)}
async function load(){data=await api('/api/dashboard');me=data.user;$('#userName').textContent=me.name;$('#userTitle').textContent=me.designation;$('#userInitials').textContent=me.name.split(' ').map(x=>x[0]).join('').slice(0,2);$('#leaveForm').email.value=me.email;render()}
function render(){const used=(me.earnedEntitlement+me.carryForward-data.balance);$('#elBalance').textContent=data.balance.toFixed(1);$('#elBar').style.width=`${Math.min(100,used/(me.earnedEntitlement+me.carryForward)*100)}%`;document.querySelector('.card small').textContent=`days remaining of ${me.earnedEntitlement+me.carryForward}`;const mine=data.requests;$('#requestRows').innerHTML=mine.map(r=>`<tr><td><b>Earned Leave${r.lwpDays?' + LWP':''}</b></td><td>${fmt(r.start)} - ${fmt(r.end)}</td><td>${r.days}</td><td>${r.reason}</td><td>${badge(r.status)}</td></tr>`).join('')||'<tr><td colspan="5">No requests yet.</td></tr>';const up=mine.find(r=>r.status==='approved'&&r.start>='2026-06-22');$('#upcoming').innerHTML=up?`<div class="dateBox">${new Date(up.start+'T00:00:00').getDate()}<small>${new Intl.DateTimeFormat('en',{month:'short'}).format(new Date(up.start+'T00:00:00')).toUpperCase()}</small></div><div><b>Earned Leave</b><p>${fmt(up.start)} - ${fmt(up.end)} · ${up.days} day${up.days===1?'':'s'}</p></div>`:'<p class="muted">No approved upcoming leave.</p>';const canApprove=['manager','hr'].includes(me.role);document.querySelectorAll('.manager').forEach(x=>x.style.display=canApprove?'flex':'none');$('#pendingBadge').textContent=data.approvals.length;$('#approvalList').innerHTML=data.approvals.map(r=>`<article class="approval"><div class="avatar">${r.employeeName.split(' ').map(x=>x[0]).join('')}</div><div><b>${r.employeeName} <span class="muted">requested ${r.days} day${r.days===1?'':'s'} earned leave${r.lwpDays?` + ${r.lwpDays} LWP`:''}</span></b><p>${fmt(r.start)} - ${fmt(r.end)} · “${r.reason}”<br>Manager: ${badge(r.managerDecision)} &nbsp; HR: ${badge(r.hrDecision)}</p></div><div class="actions"><button class="outline" onclick="decision('${r.id}','rejected')">Decline</button><button class="approve" onclick="decision('${r.id}','approved')">Approve</button></div></article>`).join('')||'<div class="panel"><p class="muted">No requests currently need your approval.</p></div>';$('#teamCalendar').innerHTML=mine.filter(r=>r.status==='approved').map(r=>`<div class="calendarRow"><div class="avatar">${me.name.split(' ').map(x=>x[0]).join('')}</div><div><b>${me.name}</b><p class="muted">Earned Leave</p></div><span>${fmt(r.start)} - ${fmt(r.end)}</span></div>`).join('')||'<p class="muted">No approved time off yet.</p>';}
window.decision=async(id,decision)=>{try{await api(`/api/leave/${id}/decision`,{method:'POST',body:JSON.stringify({decision})});await load();toast(`Request ${decision}.`)}catch(e){toast(e.message)}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const result=await api('/api/login',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});me=result.user;document.body.classList.add('loggedIn');await load();show('dashboard');if(me.mustChangePassword)toast('Please change your temporary password from your account setup.')}catch(err){$('#loginError').textContent=err.message;$('#loginError').classList.add('show')}};
$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});me=null;document.body.classList.remove('loggedIn');$('#loginForm').reset()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>show(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#quickApply').onclick=()=>show('request');
const form=$('#leaveForm');function count(){if(!form.start.value||!form.end.value)return 0;let n=0,d=new Date(form.start.value+'T00:00:00'),e=new Date(form.end.value+'T00:00:00');while(d<=e){if(d.getDay()!==0&&d.getDay()!==6)n++;d.setDate(d.getDate()+1)}return form.halfDay.checked?.5:n}form.start.onchange=()=>$('#dayCount').textContent=count();form.end.onchange=()=>$('#dayCount').textContent=count();form.halfDay.onchange=()=>$('#dayCount').textContent=count();form.onsubmit=async e=>{e.preventDefault();const f=new FormData(form);try{const r=await api('/api/leave',{method:'POST',body:JSON.stringify({start:f.get('start'),end:f.get('end'),reason:f.get('reason'),halfDay:f.get('halfDay')==='on'})});await load();form.reset();form.email.value=me.email;show('requests');toast(r.request.lwpDays?`Request submitted: ${r.request.earnedDays} EL + ${r.request.lwpDays} LWP.`:'Request sent to Manager and HR.')}catch(err){toast(err.message)}};
api('/api/session').then(async r=>{me=r.user;document.body.classList.add('loggedIn');await load();show('dashboard')}).catch(()=>{});
