const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const root = __dirname;
const types = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8'};
const sessions = new Map();
const nationalHolidays = ['2026-01-26','2026-08-15','2026-10-02'];
const festivalOptions = [
  ['Holi','2026-03-04'],['Ram Navami','2026-03-26'],['Mahavir Jayanti','2026-04-01'],['Good Friday','2026-04-03'],['Buddha Purnima','2026-05-01'],['Eid al-Fitr','2026-03-20'],['Bakrid','2026-05-27'],['Muharram','2026-06-26'],['Janmashtami','2026-09-04'],['Ganesh Chaturthi','2026-09-14'],['Dussehra','2026-10-20'],['Diwali','2026-11-08'],['Guru Nanak Jayanti','2026-11-24'],['Christmas','2026-12-25'],['New Year','2026-01-01']
].map(([name,date])=>({name,date}));
const url = process.env.SUPABASE_URL;
const anonKey = process.env.SUPABASE_ANON_KEY;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

function send(res,status,payload,headers={}) {res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(JSON.stringify(payload));}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch(e){reject(e)}})});}
function cookie(req){return (req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('pollen_session='))?.split('=')[1];}
function days(start,end,festival=[]){let n=0,d=new Date(`${start}T00:00:00`),e=new Date(`${end}T00:00:00`),off=new Set([...nationalHolidays,...festival]);while(d<=e){const iso=d.toISOString().slice(0,10);if(d.getDay()!==0&&d.getDay()!==6&&!off.has(iso))n++;d.setDate(d.getDate()+1)}return n;}
function configured(){return url&&anonKey&&serviceKey;}
async function sb(endpoint,{method='GET',body,service=false,headers={}}={}){const r=await fetch(`${url}${endpoint}`,{method,headers:{apikey:service?serviceKey:anonKey,Authorization:`Bearer ${service?serviceKey:anonKey}`,Accept:'application/json','Content-Type':'application/json',Prefer:'return=representation',...headers},body:body?JSON.stringify(body):undefined});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!r.ok)throw new Error(data.message||data.error_description||'Database request failed.');return data;}
async function getProfile(id){const rows=await sb(`/rest/v1/profiles?id=eq.${id}&select=*`,{service:true});return rows[0];}
async function current(req){const s=sessions.get(cookie(req));return s?getProfile(s.userId):null;}
async function dashboard(me){const requests=await sb(`/rest/v1/leave_requests?employee_id=eq.${me.id}&order=created_at.desc`,{service:true});const approved=requests.filter(r=>r.status==='approved').reduce((n,r)=>n+Number(r.earned_leave_days),0);let approvals=[];if(me.role==='hr')approvals=await sb('/rest/v1/leave_requests?status=eq.pending&order=created_at.desc',{service:true});if(me.role==='manager'){const people=await sb(`/rest/v1/profiles?reporting_manager_email=eq.${encodeURIComponent(me.work_email)}&select=id`,{service:true});if(people.length)approvals=await sb(`/rest/v1/leave_requests?status=eq.pending&employee_id=in.(${people.map(x=>x.id).join(',')})&order=created_at.desc`,{service:true});}const notifications=await sb(`/rest/v1/notifications?recipient_id=eq.${me.id}&order=created_at.desc&limit=10`,{service:true});return {user:me,balance:Number(me.earned_leave_entitlement)+Number(me.carry_forward)-approved,requests,approvals,notifications,nationalHolidays,festivalChoices:me.festival_holidays||[]};}
function notify(recipient_id,message){return sb('/rest/v1/notifications',{method:'POST',body:{recipient_id,message},service:true});}

http.createServer(async(req,res)=>{try{const target=new URL(req.url,'http://localhost');if(target.pathname.startsWith('/api/')&&!configured())return send(res,503,{error:'Portal configuration is incomplete. Add the Supabase environment variables.'});
if(target.pathname==='/api/login'&&req.method==='POST'){const d=await body(req);const r=await fetch(`${url}/auth/v1/token?grant_type=password`,{method:'POST',headers:{apikey:anonKey,'Content-Type':'application/json'},body:JSON.stringify({email:d.email,password:d.password})});const login=await r.json();if(!r.ok)return send(res,401,{error:'Invalid email or password.'});const profile=await getProfile(login.user.id);if(!profile)return send(res,403,{error:'Your account is not provisioned for Leave Hub.'});const token=crypto.randomBytes(32).toString('hex');sessions.set(token,{userId:profile.id});return send(res,200,{user:profile},{'Set-Cookie':`pollen_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`});}
if(target.pathname==='/api/logout'&&req.method==='POST'){sessions.delete(cookie(req));return send(res,204,{}, {'Set-Cookie':'pollen_session=; HttpOnly; Path=/; Max-Age=0'});}const me=await current(req);if(target.pathname==='/api/session')return me?send(res,200,{user:me}):send(res,401,{error:'Not signed in'});if(target.pathname.startsWith('/api/')&&!me)return send(res,401,{error:'Please sign in.'});
if(target.pathname==='/api/dashboard'){const result=await dashboard(me);result.festivalOptions=festivalOptions;return send(res,200,result);}
if(target.pathname==='/api/festival-selections'){if(!['manager','hr'].includes(me.role))return send(res,403,{error:'Manager or HR access required.'});let rows=await sb('/rest/v1/profiles?role=eq.employee&select=full_name,work_email,reporting_manager_email,festival_holidays',{service:true});if(me.role==='manager')rows=rows.filter(p=>p.reporting_manager_email===me.work_email);return send(res,200,{employees:rows,festivalOptions});}
if(target.pathname==='/api/festival-choice'&&req.method==='POST'){if(me.role!=='employee')return send(res,403,{error:'Only employees can select festival holidays.'});const d=await body(req);if(!festivalOptions.some(x=>x.date===d.date))return send(res,400,{error:'Choose a listed festival holiday.'});const selected=me.festival_holidays||[];if(selected.includes(d.date))return send(res,400,{error:'You already selected this holiday.'});if(selected.length>=5)return send(res,400,{error:'You have already selected five festival holidays.'});const [updated]=await sb(`/rest/v1/profiles?id=eq.${me.id}`,{method:'PATCH',service:true,body:{festival_holidays:[...selected,d.date]}});return send(res,200,{festivalChoices:updated.festival_holidays});}
if(target.pathname==='/api/leave'&&req.method==='POST'){if(me.role!=='employee')return send(res,403,{error:'Only employees can request leave.'});const d=await body(req);if(!d.start||!d.end||d.start>d.end)return send(res,400,{error:'Choose a valid date range.'});let total=days(d.start,d.end,me.festival_holidays||[]);if(d.halfDay){if(total!==1)return send(res,400,{error:'Half-day leave must be one working day.'});total=.5;}if(!total)return send(res,400,{error:'The selected dates contain no working days.'});const existing=await dashboard(me);const earned=Math.min(total,Math.max(0,existing.balance)),lwp=+(total-earned).toFixed(1);const [r]=await sb('/rest/v1/leave_requests',{method:'POST',service:true,body:{employee_id:me.id,start_date:d.start,end_date:d.end,total_days:total,earned_leave_days:earned,lwp_days:lwp,is_half_day:!!d.halfDay,reason:d.reason,status:'pending',manager_decision:'pending',hr_decision:'pending'}});const manager=await sb(`/rest/v1/profiles?work_email=eq.${encodeURIComponent(me.reporting_manager_email)}&select=id`,{service:true});if(manager[0])await notify(manager[0].id,`${me.full_name} submitted a leave request.`);const hr=await sb('/rest/v1/profiles?role=eq.hr&select=id',{service:true});for(const p of hr)await notify(p.id,`${me.full_name} submitted a leave request for HR approval.`);return send(res,201,{request:r});}
const m=target.pathname.match(/^\/api\/leave\/([^/]+)\/(decision|cancel)$/);if(m&&req.method==='POST'){const rows=await sb(`/rest/v1/leave_requests?id=eq.${m[1]}&select=*`,{service:true});const r=rows[0];if(!r)return send(res,404,{error:'Request not found.'});if(m[2]==='cancel'){if(r.employee_id!==me.id||!['pending','approved'].includes(r.status)||r.start_date<=new Date().toISOString().slice(0,10))return send(res,400,{error:'This request cannot be cancelled.'});const [updated]=await sb(`/rest/v1/leave_requests?id=eq.${r.id}`,{method:'PATCH',service:true,body:{status:'cancelled',updated_at:new Date().toISOString()}});return send(res,200,{request:updated});}const d=await body(req),decision=d.decision==='approved'?'approved':'rejected';if(me.role==='manager'){const person=await getProfile(r.employee_id);if(person.reporting_manager_email!==me.work_email)return send(res,403,{error:'Not your direct report.'});r.manager_decision=decision;}else if(me.role==='hr')r.hr_decision=decision;else return send(res,403,{error:'Not an approver.'});r.status=(r.manager_decision==='rejected'||r.hr_decision==='rejected')?'rejected':(r.manager_decision==='approved'&&r.hr_decision==='approved'?'approved':'pending');const [updated]=await sb(`/rest/v1/leave_requests?id=eq.${r.id}`,{method:'PATCH',service:true,body:{manager_decision:r.manager_decision,hr_decision:r.hr_decision,status:r.status,updated_at:new Date().toISOString()}});await notify(r.employee_id,r.status==='approved'?'Your leave request is approved.':r.status==='rejected'?'Your leave request was rejected.':'One approver has approved your request; it is awaiting the second approval.');return send(res,200,{request:updated});}
const safe=target.pathname==='/'?'/index.html':target.pathname;const file=path.join(root,safe);if(!file.startsWith(root)){res.writeHead(403);return res.end('Forbidden');}fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'Content-Type':types[path.extname(file)]||'application/octet-stream'});res.end(data);});
}catch(e){console.error(e);send(res,500,{error:e.message||'Unexpected error'});}}).listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('PollenIT Leave Hub running'));
